name: Release PR

on:
  push:
    branches:
      - main

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: github
          package-name: init.lua
